(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
var DisruptiveCampaign=module.exports=function(t){if(null===t||"object"!=typeof t)throw new Error("Invalid data passed to disruptive campaign");this.data=t};DisruptiveCampaign.prototype.getTaxonomyTerm=function(){var t=this.data.tax_term;if("string"==typeof t)var a=t.split(":"),i=a[1];return"string"!=typeof i?"":i},DisruptiveCampaign.prototype.getDisplayType=function(){var t=this.data.overlay_type;return"string"!=typeof t?"":t},DisruptiveCampaign.prototype.getHeadline=function(){var t=this.data.headline;return"string"!=typeof t?"":t},DisruptiveCampaign.prototype.getCampaignColor=function(){var t=this.data.campaign_hex_value;return"string"!=typeof t?"":t},DisruptiveCampaign.prototype.getSocialButtonData=function(){var t=this.data.social_buttons;return t instanceof Array?t:[]},DisruptiveCampaign.prototype.getStartDate=function(){var t=this.data.start_date;return"string"!=typeof t?"":t},DisruptiveCampaign.prototype.getEndDate=function(){var t=this.data.end_date;return"string"!=typeof t?"":t};

},{}],2:[function(require,module,exports){
var DisplayLogic=require("./DisruptiveDisplayLogic"),DisruptiveDialog=module.exports={displayDialog:function(e,o){vex.defaultOptions.className="vex-theme-disruptive-overlay";var i=$(o);vex.open({content:i.prop("outerHTML"),afterOpen:function(e){DisruptiveDialog.addBackgroundBlur();var o=$(".vex.vex-theme-disruptive-overlay"),i=$("<div/>").addClass("vex-vcenter");o.append(i),i.append(e)},beforeClose:function(){DisruptiveDialog.removeBackgroundBlur(),DisplayLogic.dismissCampaign(e)}})},closeDialog:function(e){vex.close()},addBackgroundBlur:function(e,o){e="undefined"==typeof e?"#page_root":e,o="undefined"==typeof o?"vex-blur":o,$(e).addClass(o)},removeBackgroundBlur:function(e,o){e="undefined"==typeof e?"#page_root":e,o="undefined"==typeof o?"vex-blur":o,$(e).removeClass(o)}};

},{"./DisruptiveDisplayLogic":4}],3:[function(require,module,exports){
var DisruptiveMarkup=require("./DisruptiveMarkup"),InlineBottomDisplay=require("./DisruptiveInlineBottomDisplay"),OverlayDisplay=require("./DisruptiveOverlayDisplay"),InlineTopDisplay=require("./DisruptiveInlineTopDisplay"),UrlTools=require("./UrlTools"),DisplayHandle=module.exports={campaign:{},displayFollow:function(e){var i,l=e.getDisplayType(),a=DisruptiveMarkup.getMarkup(e),n=UrlTools.getQueryVar("_dis_overlay_type");switch(DisplayHandle.campaign=e,n!==!1&&""!==n&&(l=n),l){case"overlay":i=OverlayDisplay;break;case"inline_top":i=InlineTopDisplay;break;default:i=InlineBottomDisplay}var o=window.fbAsyncInit;window.fbAsyncInit=function(){try{"function"==typeof o&&o()}catch(l){console.log("Pre-existing FB Async callback failed due to error."),console.log(l.message)}i.displayFollow(e,a),FB.XFBML.parse(),FB.Event.subscribe("edge.create",function(e,l){i.closeFollow(DisplayHandle.campaign)}),FB.Event.subscribe("edge.remove",function(e,l){i.closeFollow(DisplayHandle.campaign)}),i.showUp instanceof Function&&FB.Event.subscribe("xfbml.render",function(e,l){i.showUp()})}}};

},{"./DisruptiveInlineBottomDisplay":7,"./DisruptiveInlineTopDisplay":8,"./DisruptiveMarkup":9,"./DisruptiveOverlayDisplay":10,"./UrlTools":11}],4:[function(require,module,exports){
var DisplayLogic=module.exports={getCampaignKeyPrefix:function(e){var i=e.getTaxonomyTerm()+"_"+e.getDisplayType()+"_"+e.getCampaignColor()+"_";return i},getDismissKey:function(e){var i=DisplayLogic.getCampaignKeyPrefix(e),a=i+"dismissed";return a},getDismissDateKey:function(e){var i=DisplayLogic.getCampaignKeyPrefix(e),a=i+"date_dismissed";return a},getCampaignExpiryDateKey:function(e){var i=DisplayLogic.getCampaignKeyPrefix(e),a=i+"campaign_expiry_date";return a},dismissCampaign:function(e){if(!window.localStorage)return!1;var i=DisplayLogic.getDismissKey(e),a=DisplayLogic.getDismissDateKey(e),t=DisplayLogic.getCampaignExpiryDateKey(e),r=new Date,g=r.toISOString().slice(0,10),o=e.getEndDate();return localStorage.setItem(i,"true"),localStorage.setItem(a,g),localStorage.setItem(t,o),!0},campaignWasDismissed:function(e){if(!window.localStorage)return!1;var i=DisplayLogic.getDismissKey(e);return"true"===localStorage.getItem(i)},removeCampaignDismissal:function(e){if(!window.localStorage)return!1;var i=DisplayLogic.getDismissKey(e),a=DisplayLogic.getDismissDateKey(e);return localStorage.removeItem(i),localStorage.removeItem(a),!0},isCampaignExpired:function(e){if(!window.localStorage)return!1;var i=DisplayLogic.getCampaignExpiryDateKey(e),a=localStorage.getItem(i);if("string"==typeof a){var t=new Date(a),r=new Date;if(r>=t)return!0}return!1},campaignDismissalShouldExpire:function(e){if(!window.localStorage)return!0;var i=DisplayLogic.getDismissDateKey(e),a=localStorage.getItem(i);if("string"==typeof a){var t=new Date(a),r=new Date,g=new Date;if(g.setDate(t.getDate()+7),r>=g)return!0}return!1}};

},{}],5:[function(require,module,exports){
module.exports={campaignExists:function(e){return e="undefined"!=typeof e?e:"meta[name='ao:disruptive-follow']",$(e).length>0},getCampaignData:function(e){e="undefined"!=typeof e?e:"meta[name='ao:disruptive-follow']";var t=!1,n=$(e);if(n.length>0)var a=n.attr("content"),t=$.parseJSON(a);return t}};

},{}],6:[function(require,module,exports){
var DisruptiveDisplayHandle=require("./DisruptiveDisplayHandle");module.exports={triggerCampaignFoundEvent:function(i){if(null===i||"object"!=typeof i)throw new Error("Invalid campaign passed to event trigger");$(document).trigger("AOCore:disruptive_follow:campaign_found",i)},bindDisruptiveEvent:function(){$(document).on("AOCore:disruptive_follow:campaign_found",function(i,e){DisruptiveDisplayHandle.displayFollow(e)})}};

},{"./DisruptiveDisplayHandle":3}],7:[function(require,module,exports){
module.exports={displayFollow:function(o,l){var e=$(l);e.addClass("dis-type-inline-bottom"),e.insertBefore("div.author")},closeFollow:function(o){}};

},{}],8:[function(require,module,exports){
var DisplayLogic=require("./DisruptiveDisplayLogic"),UrlTools=require("./UrlTools"),InlineTopDisplay=module.exports={displayFollow:function(i,s){var o=!1,l=UrlTools.getQueryVar("_dis_clear_close_record"),a=DisplayLogic.isCampaignExpired(i);if(DisplayLogic.campaignDismissalShouldExpire(i)&&DisplayLogic.removeCampaignDismissal(i),"1"===l?(DisplayLogic.removeCampaignDismissal(i),o=!1,a=!1):DisplayLogic.campaignWasDismissed(i)&&(o=!0),!o&&!a){var e=$(s),n=$("<div/>").addClass("dis-top-container").addClass("dis-top-close");e.addClass("dis-type-inline-top"),n.append(e),n.insertAfter(".navbar"),InlineTopDisplay.bindInlineTopDisplayEvents(i)}},showUp:function(){$(".dis-top-container").removeClass("dis-top-close")},closeFollow:function(i){DisplayLogic.dismissCampaign(i),$(".dis-top-container").addClass("dis-top-close")},bindInlineTopDisplayEvents:function(i){$(".dis-type-inline-top").click(function(s){InlineTopDisplay.closeFollow(i)})}};

},{"./DisruptiveDisplayLogic":4,"./UrlTools":11}],9:[function(require,module,exports){
module.exports={getMarkup:function(a){var t=a.getSocialButtonData(),o=$("<div/>").addClass("disruptive-campaign"),e=$("<span/>").addClass("icon-logo-mtv icon-logo-brand").css("background-color",a.getCampaignColor()),s=$("<div>").addClass("logo-container").css("background-color",a.getCampaignColor()),n=$("<span/>").addClass("icon-actions-close"),d=$("<div/>").addClass("social-btns"),l=$("<div/>").addClass("rightbox"),r=a.getHeadline();r=r.replace(/\s\*/," <span>"),r=r.replace(/\*\s/,"</span> ");var c=$("<span/>").addClass("headline").html(r);if(c.children().css("background-color",a.getCampaignColor()),t.length>0){for(x=0;x<t.length;x++)if("facebook_like"===t[x].name)var i=$("<div/>").addClass("fb-like").attr("data-href","https://www.facebook.com/"+t[x].account).attr("data-layout","button_count").attr("data-action","like").attr("data-show-faces","false").attr("data-share","false");else if("twitter"===t[x].name)var p=$("<a/>").attr("href","https://twitter.com/"+t[x].account).addClass("twitter-follow-button").attr("data-show-count","true").attr("data-show-screen-name","false").text("Follow @"+t[x].account);d.append(i,p)}return l.append(n,c,d),s.append(e),o.append(s,l),o}};

},{}],10:[function(require,module,exports){
var DisruptiveDialog=require("./DisruptiveDialog"),DisplayLogic=require("./DisruptiveDisplayLogic"),UrlTools=require("./UrlTools");module.exports={displayFollow:function(i,o){var s=!1,e=UrlTools.getQueryVar("_dis_clear_close_record"),a=DisplayLogic.isCampaignExpired(i);if(DisplayLogic.campaignDismissalShouldExpire(i)&&DisplayLogic.removeCampaignDismissal(i),"1"===e?(DisplayLogic.removeCampaignDismissal(i),s=!1,a=!1):DisplayLogic.campaignWasDismissed(i)&&(s=!0),!s&&!a){var l=$(o),r="";l.addClass("dis-type-overlay"),r=$("#commentsContainer").length?$("#commentsContainer"):$(".author .description"),r.on("inview",function(o){DisruptiveDialog.displayDialog(i,l),$(this).off(o),"undefined"!=typeof FB&&"undefined"!=typeof FB.XFBML&&FB.XFBML.parse()})}},closeFollow:function(i){DisruptiveDialog.closeDialog(i)}};

},{"./DisruptiveDialog":2,"./DisruptiveDisplayLogic":4,"./UrlTools":11}],11:[function(require,module,exports){
var UrlTools=module.exports={getQueryVars:function(r){r="undefined"==typeof selector?location.search:r;var e={};if(r.length>0){"?"===r.charAt(0)&&(r=r.substr(1));var t,n,o,s;for(t=r.split("&"),o=0,s=t.length;s>o;o++)n=t[o].split("="),e[n[0]]=n[1]}return e},getQueryVar:function(r){if("string"!=typeof r)return!1;var e=UrlTools.getQueryVars();return"undefined"==typeof e[r]?!1:e[r]}};

},{}],12:[function(require,module,exports){
var DisruptiveCampaign=require("./lib/DisruptiveCampaign"),DisruptiveDomData=require("./lib/DisruptiveDomData"),DisruptiveEventHandle=require("./lib/DisruptiveEventHandle");!function(e,i,t){DisruptiveEventHandle.bindDisruptiveEvent(),e(document).ready(function(){if(DisruptiveDomData.campaignExists())try{var e=DisruptiveDomData.getCampaignData(),i=new DisruptiveCampaign(e),t=new Date(i.getStartDate()),a=new Date,n=new Date(i.getEndDate());if(!(a>=t&&n>=a))throw new Error("Campaign is not within date range.");DisruptiveEventHandle.triggerCampaignFoundEvent(i)}catch(r){console.log("Unable to send campaign event."),console.log(r.message)}})}(jQuery,window,void 0);
},{"./lib/DisruptiveCampaign":1,"./lib/DisruptiveDomData":5,"./lib/DisruptiveEventHandle":6}]},{},[12]);
